version: "2"
services:
  server:
    build:
      context: ./server
    command: yarn run watch
    ports:
      - "3300:3100"
    volumes:
      - ./server:/server
      - /home/sam/Dropbox/Apps/Iexpense lite:/server/data
